Repository massgov/mayflower-react, pull requests merged in 2018-06, with the labels that each got.

#212 DP-9100: Changes dots to dashes for utilitynav nav content divs.
  package-lock.json
  package.json
  src/components/organisms/UtilityNav/index.js
Labels: Ready for External Review

#217 DP-9122 [a11y]: Adds Context to Pagination Molecule
  src/components/molecules/Pagination/Pagination.knobs.options.js
  src/components/molecules/Pagination/Pagination.stories.js
  src/components/molecules/Pagination/index.js
Labels: Ready for External Review

#213 prep imagePromo for rendering orgInfo
  src/components/atoms/media/Image/index.js
  src/components/molecules/ImagePromo/ImagePromo.stories.js
  src/components/molecules/ImagePromo/index.js
  src/components/molecules/ImagePromo/style.scss
  src/components/molecules/OrgSelector/index.js
Labels: Ready for External Review

#216 Feature/dp 9196 further typeahead fixes
  src/components/atoms/forms/InputTextTypeAhead/index.js
  src/components/molecules/OrgSelector/OrgSelector.stories.js
  src/components/molecules/TypeAheadDropdown/TypeAheadDropdown.stories.js
  src/components/molecules/TypeAheadDropdown/index.js
Labels: Ready for External Review

#209 DP-9130 add inputTextTypeahead Org dropdown to SearchBanner
  src/components/atoms/forms/InputTextTypeAhead/InputTextTypeAhead.knobs.options.js
  src/components/atoms/forms/InputTextTypeAhead/index.js
  src/components/atoms/forms/InputTextTypeAhead/style.scss
  src/components/molecules/HeaderSearch/HeaderSearch.scss
  src/components/molecules/HeaderSearch/HeaderSearch.stories.js
  src/components/molecules/HeaderSearch/index.js
  src/components/molecules/TypeAheadDropdown/index.js
  src/components/molecules/TypeAheadDropdown/style.scss
  src/components/organisms/FilterBox/FilterBox.props.js
  src/components/organisms/FilterBox/FilterBox.stories.js
  src/components/organisms/FilterBox/index.js
  src/components/organisms/FilterBox/style.scss
  src/components/organisms/SearchBanner/SearchBanner.stories.js
  src/components/organisms/SearchBanner/index.js
  src/components/organisms/SearchBanner/style.scss
Labels: Ready for Internal Review

#220 bump version to 0.41.0
  package-lock.json
  package.json
Labels: Ready for External Review

#222 Fix handling of filterbox submit callbacks
  src/components/organisms/SearchBanner/index.js
Labels: Ready for External Review

#223 Fix image promo condition
  src/components/molecules/ImagePromo/index.js
Labels: Ready for External Review

#228 DP-9235: Fix for Attention Greedy OrgFilter in HeaderSearch
  src/components/molecules/HeaderSearch/HeaderSearch.scss
  src/components/molecules/HeaderSearch/index.js
Labels: Ready for External Review

#227 Fix for date range not staying in FilterBox
  src/components/atoms/forms/InputDate/index.js
  src/components/organisms/SearchBanner/SearchBanner.stories.js
Labels: Ready for Internal Review

#232 bump to version 0.41.3
  package-lock.json
  package.json
Labels: Ready for Internal Review

#219 DP-9230 make outer callback handling less confusing/ more consistent
  src/components/molecules/TypeAheadDropdown/index.js
Labels: Ready for External Review

#234 DP-9253 fix dropdown not closing on blur, set focus on Esc.
  src/components/atoms/buttons/ButtonWithIcon/index.js
  src/components/atoms/forms/InputTextTypeAhead/index.js
  src/components/molecules/TypeAheadDropdown/index.js
Labels: Ready for External Review

#235 DP-9120: Adds new DownloadLink component.
  src/components/atoms/icons/SvgDocDocx/index.js
  src/components/atoms/icons/SvgDocGeneric/index.js
  src/components/atoms/icons/SvgDocPdf/index.js
  src/components/atoms/icons/SvgDocXlxs/index.js
  src/components/atoms/links/DecorativeLink/DecorativeLink.knob.options.js
  src/components/atoms/links/DecorativeLink/DecorativeLink.md
  src/components/atoms/links/DecorativeLink/DecorativeLink.scss
  src/components/atoms/links/DecorativeLink/index.js
Labels: Ready for External Review

#238 Add generic file icon to download link
  src/components/atoms/icons/SvgDocDocx/index.js
  src/components/atoms/icons/SvgDocGeneric/index.js
  src/components/atoms/icons/SvgDocPdf/index.js
  src/components/atoms/icons/SvgDocXlxs/index.js
  src/components/atoms/links/DecorativeLink/index.js
Labels: Ready for External Review

#239 bump to mayflower-react to version 0.42.1
  package-lock.json
  package.json
Labels: Ready for External Review, Ready for Internal Review

#242 DP-9307 fix Org filter close on mouse scrollbar interaction / various fixes & cleanup in HeaderSearch components/stories
  src/components/atoms/forms/InputTextTypeAhead/InputTextTypeAhead.knobs.options.js
  src/components/atoms/forms/InputTextTypeAhead/InputTextTypeAhead.stories.js
  src/components/molecules/HeaderSearch/HeaderSearch.scss
  src/components/molecules/HeaderSearch/index.js
  src/components/molecules/ResultsHeading/index.js
  src/components/molecules/TypeAheadDropdown/index.js
  src/components/organisms/FilterBox/FilterBox.stories.js
  src/components/organisms/FilterBox/index.js
  src/components/organisms/PressFilters/PressFilters.stories.js
  src/components/organisms/PressFilters/index.js
Labels: Ready for External Review

#240 move org filter into filterbox on mobile
  src/components/molecules/HeaderSearch/HeaderSearch.scss
  src/components/molecules/HeaderSearch/index.js
  src/components/organisms/SearchBanner/SearchBanner.stories.js
  src/components/organisms/SearchBanner/style.scss
Labels: Ready for External Review

#243 secondary button accessibility contrast fix
  src/components/atoms/buttons/Button/index.js
  src/components/atoms/buttons/Button/style.scss
  src/components/atoms/buttons/ButtonWithIcon/style.scss
  src/components/styles/_colors.scss
Labels: Ready for External Review

#246 DP-9358: Do not close input text on clear of input value
  src/components/molecules/TypeAheadDropdown/index.js
Labels: Ready for External Review

#247 bump mayflower-react to version 0.43.1
  package-lock.json
  package.json
Labels: Ready for External Review

#251 DP-9372 fix overflow
  src/components/molecules/HeaderSearch/HeaderSearch.scss
Labels: Ready for Internal Review

#249 DP-9369 add clearbutton to search input
  src/components/molecules/HeaderSearch/HeaderSearch.scss
  src/components/molecules/HeaderSearch/index.js
Labels: Ready for Internal Review

#132 Update Table Atom Component
  src/components/atoms/table/Table/Table.knobs.options.js
  src/components/atoms/table/Table/Table.md
  src/components/atoms/table/Table/Table.stories.js
  src/components/atoms/table/Table/index.js
Labels: Ready for External Review
