Repository massgov/mayflower-react, pull requests merged in 2018-05, with the labels that each got.

#164 add selectbox into resultsHeading
  src/components/atoms/forms/SelectBox/SelectBox.stories.js
  src/components/atoms/forms/SelectBox/index.js
  src/components/atoms/forms/SelectBox/style.scss
  src/components/molecules/OrgSelector/OrgSelector.stories.js
  src/components/molecules/ResultsHeading/ResultsHeading.knobs.options.js
  src/components/molecules/ResultsHeading/ResultsHeading.stories.js
  src/components/molecules/ResultsHeading/index.js
  src/components/molecules/ResultsHeading/style.scss
  src/components/organisms/PressFilters/PressFilters.stories.js
  src/components/styles/_breakpoints.scss
  src/components/styles/_variables.scss
  src/index.js
Labels: Ready for Internal Review

#163 DP-8754: Pass type ahead to orgselector.
  src/components/atoms/forms/InputTextTypeAhead/index.js
  src/components/molecules/OrgSelector/OrgSelector.stories.js
  src/components/molecules/OrgSelector/index.js
Labels: Ready for Internal Review

#165 Dp 8873 pass orgselector typeahead to pressfilter
  src/components/atoms/forms/InputTextTypeAhead/InputTextTypeAhead.stories.js
  src/components/atoms/forms/SelectBox/SelectBox.stories.js
  src/components/atoms/forms/SelectBox/index.js
  src/components/molecules/OrgSelector/index.js
  src/components/molecules/OrgSelector/style.scss
  src/components/molecules/ResultsHeading/ResultsHeading.stories.js
  src/components/organisms/PressFilters/PressFilters.stories.js
Labels: Ready for Internal Review, next release

#166 DP-8755 add typeahead input option for presstype selector in pressFilter
  src/components/atoms/forms/InputTextTypeAhead/InputTextTypeAhead.stories.js
  src/components/organisms/PressFilters/PressFilters.stories.js
  src/components/organisms/PressFilters/index.js
  src/components/organisms/PressFilters/style.scss
Labels: Ready for Internal Review, next release

#161 Lint fixes pagination
  src/components/molecules/Pagination/Pagination.knobs.options.js
  src/components/molecules/Pagination/Pagination.stories.js
  src/components/molecules/Pagination/index.js
Labels: Ready for External Review

#172 scrollable and limit height of typeaheads used in the press filter
  src/components/atoms/forms/InputTextTypeAhead/style.scss
  src/components/atoms/forms/SelectBox/SelectBox.knobs.options.js
  src/components/molecules/OrgSelector/OrgSelector.knobs.options.js
  src/components/organisms/PressFilters/PressFilters.stories.js
  src/components/organisms/PressFilters/style.scss
Labels: Ready for External Review

#171 render clear button in typeahead
  src/components/atoms/forms/InputTextTypeAhead/index.js
  src/components/atoms/forms/InputTextTypeAhead/style.scss
Labels: Ready for External Review

#176 fix suggetion highlight
  src/components/atoms/forms/InputTextTypeAhead/style.scss
Labels: Ready for Internal Review, bug

#175 update readme
  .gitignore
  README.md
Labels: Ready for External Review, Ready for Internal Review

#181 Update site logo
  package-lock.json
  package.json
  src/components/atoms/media/SiteLogo/index.js
  src/components/atoms/media/SiteLogo/mass-logo.png
  src/components/atoms/media/SiteLogo/stateseal.png
Labels: Ready for External Review

#182 Removes un-needed grouping tags from chevron.
  src/components/atoms/icons/SvgChevron/index.js
Labels: Ready for Internal Review

#187 Adds regex escaping to autosuggestions.
  src/components/atoms/forms/InputTextTypeAhead/index.js
Labels: Ready for External Review

#191 Feature/dp 9000 svg ids
  src/components/atoms/icons/SvgArrow/index.js
  src/components/atoms/icons/SvgArrowBent/index.js
  src/components/atoms/icons/SvgBuilding/index.js
  src/components/atoms/icons/SvgFax/index.js
  src/components/atoms/icons/SvgLaptop/index.js
  src/components/atoms/icons/SvgLogin/index.js
  src/components/atoms/icons/SvgMarker/index.js
  src/components/atoms/icons/SvgPhone/index.js
Labels: Ready for Internal Review

#190 DP-8909 fix OrgSelector propTypes
  src/components/molecules/OrgSelector/index.js
Labels: Ready for Internal Review

#192 DP-9001 add aria-label property to ButtonSearch
  src/components/atoms/buttons/ButtonSearch/ButtonSearch.knobs.options.js
  src/components/atoms/buttons/ButtonSearch/ButtonSearch.md
  src/components/atoms/buttons/ButtonSearch/ButtonSearch.stories.js
  src/components/atoms/buttons/ButtonSearch/index.js
  src/components/molecules/HeaderSearch/HeaderSearch.stories.js
  src/components/molecules/HeaderSearch/index.js
  src/components/molecules/SearchBannerForm/SearchBannerForm.stories.js
  src/components/organisms/Header/Header.stories.js
Labels: Ready for External Review

#193 Fix linter no-param-reassign warning in SearchBannerForm
  src/components/molecules/SearchBannerForm/SearchBannerForm.stories.js
  src/components/molecules/SearchBannerForm/index.js
Labels: Ready for External Review

#195 Version bump
  package-lock.json
  package.json
Labels: Ready for External Review, Ready for Internal Review

#194 DP-8995: Add AdvancedSearchBox Organism to Mayflower-React
  src/components/organisms/FilterBox/FilterBox.stories.js
  src/components/organisms/FilterBox/index.js
  src/components/organisms/FilterBox/style.scss
  src/components/styles/_colors.scss
  src/index.js
Labels: Ready for Internal Review

#199 set default scss import path
  package.json
  src/components/atoms/buttons/ButtonWithIcon/style.scss
  src/components/atoms/forms/InputTextTypeAhead/style.scss
  src/components/molecules/ResultsHeading/style.scss
  src/components/organisms/FilterBox/style.scss
Labels: Ready for External Review

#198 Add type ahead dropdown molecule
  src/components/atoms/buttons/ButtonWithIcon/ButtonWithIcon.stories.js
  src/components/atoms/buttons/ButtonWithIcon/index.js
  src/components/atoms/buttons/ButtonWithIcon/style.scss
  src/components/atoms/forms/InputTextTypeAhead/InputTextTypeAhead.stories.js
  src/components/atoms/forms/InputTextTypeAhead/index.js
  src/components/atoms/forms/InputTextTypeAhead/style.scss
  src/components/molecules/TypeAheadDropdown/TypeAheadDropdown.stories.js
  src/components/molecules/TypeAheadDropdown/index.js
  src/components/organisms/LinkList/LinkList.stories.js
  src/components/organisms/LinkList/index.js
  src/index.js
Labels: Ready for External Review

#200 add search banner with tabs
  src/components/molecules/Tabs/Tabs.knobs.options.js
  src/components/molecules/Tabs/Tabs.stories.js
  src/components/molecules/Tabs/index.js
  src/components/molecules/Tabs/style.scss
  src/components/organisms/SearchBanner/SearchBanner.stories.js
  src/components/organisms/SearchBanner/index.js
  src/components/organisms/SearchBanner/style.scss
  src/index.js
Labels: Ready for Internal Review

#207 Fix 4 "no-unused-vars" eslint warnings from FilterBox
  src/components/organisms/FilterBox/FilterBox.stories.js
Labels: Ready for External Review

#203 Close Button/TypeAhead on Click outside
  package-lock.json
  src/components/atoms/buttons/ButtonWithIcon/index.js
  src/components/atoms/forms/InputTextTypeAhead/index.js
  src/components/molecules/TypeAheadDropdown/index.js
Labels: Ready for External Review

#210 Fix React warnings for missing keys in li elements
  src/components/organisms/LinkList/LinkList.stories.js
  src/components/organisms/LinkList/index.js
Labels: Ready for Internal Review

#211 In 82335ec mayflower was updated in package-lock without the integrit…
  package-lock.json
Labels: Ready for External Review
